/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Primary — Forest Teal (Collision: kept existing)
        primary: {
          DEFAULT: '#0B4F45',
          dark: '#073A33',
        },
        // Accent — Sunclay
        accent: {
          DEFAULT: '#C75B30',
          light: '#E79868',
        },
        // Backgrounds & surfaces (Collision on surface: kept existing)
        warm: '#FAF7F2',
        surface: '#FFFFFF',
        // Text colors
        charcoal: '#1B1F1D',
        body: '#4A4F4C',
        muted: '#8A8F8B',
        border: '#E5E1DA',
        // Semantic colors (Collision on error: kept existing)
        success: '#1E9E6A',
        warning: '#E8A23D',
        error: '#D14343',
        info: '#3B7DD8',
        // Dashboard sidebar dark
        sidebar: {
          bg: '#0E2522',
          text: '#F4F1EA',
        },
        // Merged from export
        "inverse-on-surface": "#eef1ee",
        "surface-container-low": "#f1f4f1",
        "surface-variant": "#e0e3e0",
        "secondary-fixed-dim": "#a1d0c6",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#ffdbcf",
        "surface-tint": "#2c685d",
        "surface-container-highest": "#e0e3e0",
        "primary-container": "#0b4f45",
        "on-secondary-container": "#3e6b62",
        "secondary": "#3a665e",
        "tertiary": "#591a00",
        "surface-bright": "#f7faf6",
        "on-error": "#ffffff",
        "inverse-primary": "#96d2c5",
        "on-background": "#181c1a",
        "on-tertiary-fixed": "#380d00",
        "error-container": "#ffdad6",
        "surface-dim": "#d8dbd7",
        "on-primary-fixed-variant": "#0d5046",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#2d312f",
        "on-secondary-fixed-variant": "#214e47",
        "primary-fixed": "#b1efe1",
        "secondary-container": "#bae9df",
        "tertiary-fixed-dim": "#ffb59b",
        "surface-container": "#ecefeb",
        "on-error-container": "#93000a",
        "on-secondary-fixed": "#00201b",
        "on-surface-variant": "#404946",
        "on-tertiary-fixed-variant": "#812900",
        "outline-variant": "#bfc9c5",
        "tertiary-container": "#7f2800",
        "on-surface": "#181c1a",
        "background": "#f7faf6",
        "on-primary-fixed": "#00201b",
        "on-tertiary-container": "#ff9973",
        "surface-container-high": "#e6e9e5",
        "outline": "#707976",
        "on-tertiary": "#ffffff",
        "on-primary-container": "#84bfb2",
        "primary-fixed-dim": "#96d2c5",
        "on-primary": "#ffffff",
        "secondary-fixed": "#bdece1",
      },
      fontFamily: {
        display: ['Cabinet Grotesk', 'Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        "data-mono": ["JetBrains Mono"],
        "body-sm": ["Inter"],
        "body-lg": ["Inter"],
        "headline-md": ["Sora"],
        "display-lg-mobile": ["Sora"],
        "label-caps": ["Inter"],
        "display-lg": ["Sora"],
      },
      fontSize: {
        'display': ['56px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-sm': ['36px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'h2': ['40px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
        'h2-sm': ['28px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
        'h3': ['28px', { lineHeight: '1.3', fontWeight: '600' }],
        'h3-sm': ['22px', { lineHeight: '1.3', fontWeight: '600' }],
        'h4': ['20px', { lineHeight: '1.4', fontWeight: '600' }],
        'h4-sm': ['18px', { lineHeight: '1.4', fontWeight: '600' }],
        'body': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'small': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'micro': ['12px', { lineHeight: '1.4', fontWeight: '500' }],
        "data-mono": ["13px", {"lineHeight": "18px", "letterSpacing": "0.02em", "fontWeight": "500"}],
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-md": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "display-lg-mobile": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "label-caps": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
      },
      spacing: {
        'sidebar-width': '260px',
        'container-padding': '24px',
        'card-gap': '20px',
        'gutter': '16px',
        'base': '8px',
      },
      borderRadius: {
        'sm': '4px',
        DEFAULT: '8px',
        'lg': '12px',
        'xl': '16px',
        'full': '9999px',
      },
      boxShadow: {
        'sm': '0 1px 2px rgba(27,31,29,0.06)',
        'md': '0 8px 24px rgba(27,31,29,0.08)',
        'lg': '0 24px 48px rgba(27,31,29,0.12)',
        'card': '0 1px 2px rgba(27,31,29,0.06)',
        'card-hover': '0 8px 24px rgba(27,31,29,0.08)',
      },
      maxWidth: {
        'marketing': '1280px',
        'dashboard': '1440px',
        'auth-card': '440px',
      },
      transitionTimingFunction: {
        'out-expo': 'cubic-bezier(0.16, 1, 0.3, 1)',
      },
      animation: {
        'shimmer': 'shimmer 1.5s infinite',
        'float': 'float 6s ease-in-out infinite',
        'pulse-slow': 'pulse 3s ease-in-out infinite',
        'count-up': 'countUp 0.8s ease-out forwards',
        'fade-up': 'fadeUp 0.5s ease-out forwards',
        'spin-slow': 'spin 3s linear infinite',
      },
      keyframes: {
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-12px)' },
        },
        fadeUp: {
          '0%': { opacity: '0', transform: 'translateY(16px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
      backgroundImage: {
        'gradient-warm': 'linear-gradient(135deg, #0B4F45 0%, #073A33 50%, #0B4F45 100%)',
        'gradient-accent': 'linear-gradient(135deg, #C75B30 0%, #E79868 100%)',
        'shimmer-gradient': 'linear-gradient(90deg, #f0ece4 25%, #e8e3da 50%, #f0ece4 75%)',
      },
    },
  },
  plugins: [],
}
