/**
 * Document Generator Utility
 * Generates valid pure-JavaScript binary PDF files and triggers direct browser file download with .pdf extension.
 */

const buildPurePDFBlob = (docTitle, linesArray) => {
  const wrappedLines = [];
  linesArray.forEach(line => {
    if (line === null || line === undefined || line === '') {
      wrappedLines.push('');
      return;
    }
    const str = String(line);
    let current = '';
    const words = str.split(' ');
    words.forEach(w => {
      if ((current + ' ' + w).trim().length > 70) {
        wrappedLines.push(current.trim());
        current = w;
      } else {
        current = (current + ' ' + w).trim();
      }
    });
    if (current) wrappedLines.push(current);
  });

  const linesPerPage = 38;
  const pages = [];
  for (let i = 0; i < wrappedLines.length; i += linesPerPage) {
    pages.push(wrappedLines.slice(i, i + linesPerPage));
  }
  if (pages.length === 0) pages.push(['(No content provided)']);

  const pageObjects = [];
  const contentObjects = [];
  let objId = 5;

  pages.forEach((pageLines, pIdx) => {
    const pageObjId = objId++;
    const streamObjId = objId++;
    pageObjects.push(pageObjId);

    let streamText = 'BT\n/F2 15 Tf\n50 740 Td\n';
    const cleanTitle = pIdx === 0 ? docTitle : `${docTitle} (Page ${pIdx + 1})`;
    streamText += `(${cleanTitle.replace(/[\(\)\\]/g, '\\$&')}) Tj\n`;
    streamText += '/F1 10 Tf\n0 -28 Td\n';

    pageLines.forEach(line => {
      if (line.startsWith('### ')) {
        streamText += '/F2 11 Tf\n0 -22 Td\n';
        streamText += `(${line.replace(/^### /, '').replace(/[\(\)\\]/g, '\\$&')}) Tj\n`;
        streamText += '/F1 10 Tf\n0 -16 Td\n';
      } else {
        streamText += `(${line.replace(/[\(\)\\]/g, '\\$&')}) Tj\n`;
        streamText += '0 -15 Td\n';
      }
    });
    streamText += 'ET';

    contentObjects.push({ pageObjId, streamObjId, streamText });
  });

  let pdf = `%PDF-1.4\n`;
  const offsets = [0];

  const addObj = (id, str) => {
    offsets[id] = pdf.length;
    pdf += `${id} 0 obj\n${str}\nendobj\n`;
  };

  addObj(1, `<< /Type /Catalog /Pages 2 0 R >>`);
  const kidsStr = pageObjects.map(id => `${id} 0 R`).join(' ');
  addObj(2, `<< /Type /Pages /Kids [${kidsStr}] /Count ${pageObjects.length} >>`);
  addObj(3, `<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>`);
  addObj(4, `<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>`);

  contentObjects.forEach(({ pageObjId, streamObjId, streamText }) => {
    addObj(pageObjId, `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents ${streamObjId} 0 R /Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> >>`);
    addObj(streamObjId, `<< /Length ${streamText.length} >>\nstream\n${streamText}\nendstream`);
  });

  const xrefOffset = pdf.length;
  pdf += `xref\n0 ${objId}\n0000000000 65535 f \n`;
  for (let i = 1; i < objId; i++) {
    pdf += `${(offsets[i] || 0).toString().padStart(10, '0')} 00000 n \n`;
  }
  pdf += `trailer\n<< /Size ${objId} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;

  return new Blob([pdf], { type: 'application/pdf' });
};

export const triggerFileDownload = (content, filename, mimeType = 'application/pdf') => {
  const blob = content instanceof Blob ? content : new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
};

export const downloadReceiptDoc = (receipt = {}) => {
  const lines = [
    'OFFICIAL TENANCY PAYMENT RECEIPT',
    '========================================================================',
    `Receipt Reference: ${receipt.id || 'RF-2026-1001'}`,
    `Issue Date: ${receipt.date || 'Jun 01, 2026'}`,
    `Payment Status: VERIFIED & SETTLED`,
    '',
    '### RESIDENT & PROPERTY INFORMATION',
    `Tenant Name: Ayomikun Adeleke`,
    `Property: Victoria Island Towers, Suite 402-B`,
    `Address: Ahmadu Bello Way, Victoria Island, Lagos`,
    '',
    '### TRANSACTION BREAKDOWN',
    `Description: ${receipt.title || 'Monthly Rent Payment Settlement'}`,
    `Payment Category: ${receipt.type || 'Rent & Service Charge'}`,
    `Billing Cycle: ${receipt.year || '2026'} Schedule`,
    `Payment Method: ${receipt.method || 'Automated Bank Direct Debit'}`,
    '',
    '------------------------------------------------------------------------',
    `TOTAL AMOUNT SETTLED: ${receipt.amount || '₦3,250,000'}`,
    '------------------------------------------------------------------------',
    '',
    '### MANAGEMENT NOTES & CERTIFICATION',
    'This electronic receipt is digitally generated by RentFlow Portal and verified',
    'against bank clearing records. No signature is required for statutory compliance.',
    'For inquiries regarding this reconciliation, contact billing@victoriaislandtowers.ng.',
    '',
    `Archive Verification Code: SHA256-${Math.random().toString(36).substring(2, 10).toUpperCase()}-LAG`
  ];

  const blob = buildPurePDFBlob(`Official Receipt - ${receipt.id || 'RF-2026-1001'}`, lines);
  triggerFileDownload(blob, `RentFlow_Receipt_${receipt.id || 'RF-2026-1001'}.pdf`, 'application/pdf');
};

export const downloadLeaseDoc = () => {
  const lines = [
    'OFFICIAL LEASE AGREEMENT & TENANCY CONTRACT',
    '========================================================================',
    'Contract ID: RF-8921-LG | Property: Victoria Island Towers, Unit #402-B',
    'Effective Term: January 1, 2026 – December 31, 2026',
    '',
    '### PARTIES TO THE AGREEMENT',
    'Landlord/Manager: Adeleke & Co. Management Ltd.',
    'Resident/Tenant: Ayomikun Adeleke (Verified Identity: ID-NG-889410)',
    '',
    '### 1. FINANCIAL CONSIDERATION & SCHEDULE',
    'The Tenant agrees to settle the annual base rent of ₦34,200,000 payable in',
    'agreed quarterly or monthly installments as outlined in Schedule A. All payments',
    'must be executed via approved digital bank channels or portal Direct Debit.',
    '',
    '### 2. USE OF PREMISES & OCCUPANCY RESTRICTIONS',
    'The residential apartment is leased exclusively as a private dwelling for the',
    'registered resident and authorized immediate family members. Subletting, short-let',
    'operations, or unauthorized commercial activities are strictly prohibited.',
    '',
    '### 3. MAINTENANCE, REPAIRS & PROPERTY CARE',
    'The Landlord maintains structural integrity, building plumbing, and heavy electrical',
    'mains. The Resident is responsible for internal cleanliness, routine fixture care,',
    'and reporting minor defects within 48 hours via the portal maintenance desk.',
    '',
    '### 4. PARKING & VEHICLE ACCESS',
    'Resident is allocated designated subterranean Parking Stall #42. Visitor vehicles',
    'must register at the security gatehouse and utilize designated guest bays only.',
    '',
    '### SIGNATURE VERIFICATION',
    'Electronically Signed by Ayomikun Adeleke on Dec 15, 2025 (SHA-256 Hash Verified)',
    'Countersigned by Adeleke & Co. Management Ltd.'
  ];

  const blob = buildPurePDFBlob('Full Lease Agreement - RF-8921-LG', lines);
  triggerFileDownload(blob, 'RentFlow_Full_Lease_Agreement_RF-8921-LG.pdf', 'application/pdf');
};

export const downloadAnnualReportDoc = () => {
  const lines = [
    '2026 ANNUAL TENANCY & FINANCIAL SUMMARY REPORT',
    '========================================================================',
    'Prepared For: Ayomikun Adeleke | Unit #402-B, Victoria Island Towers',
    `Report Generation Date: ${new Date().toLocaleDateString('en-US', { dateStyle: 'long' })}`,
    '',
    '### EXECUTIVE FINANCIAL OVERVIEW',
    'Total Rent Settled (YTD): ₦34,200,000.00',
    'Service & Utility Contributions: ₦2,400,000.00',
    'Security Deposit Held in Trust: ₦2,500,000.00',
    'Current Account Balance: ₦0.00 (Fully Reconciled & Up to Date)',
    '',
    '### MAINTENANCE & AUDIT TRAIL',
    'Total Requests Logged: 4 | Completed: 4 | Average Resolution: 18.5 Hours',
    'Annual HVAC Filter Servicing: Completed successfully on April 12, 2026.',
    'Fire Safety Audit & Sensor Calibration: Passed on May 03, 2026.',
    '',
    '### PROPERTY MANAGEMENT ENDORSEMENT',
    'Adeleke & Co. Management certifies that the tenancy of Unit #402-B is in absolute',
    'good standing with no outstanding encumbrances, penalties, or compliance breaches.'
  ];

  const blob = buildPurePDFBlob('2026 Annual Tenancy Summary Report', lines);
  triggerFileDownload(blob, 'RentFlow_2026_Annual_Report.pdf', 'application/pdf');
};

export const downloadDataExportJSON = (data) => {
  const exportPayload = data || {
    tenant: {
      fullName: 'Ayomikun Adeleke',
      preferredName: 'Ayo',
      email: 'ayomikun.adeleke@rentflows.ng',
      phone: '+234 803 123 4567',
      unit: '#402-B',
      property: 'Victoria Island Towers, Suite 402, Lagos, Nigeria',
      leaseId: 'RF-8921-LG',
      twoFactorEnabled: true,
      emergencyContacts: [
        { name: 'Chidinma Adeleke', relation: 'Spouse', phone: '+234 802 987 6543' },
        { name: 'Babatunde Adeleke', relation: 'Brother', phone: '+234 803 234 5678' }
      ]
    },
    exportDate: new Date().toISOString()
  };
  triggerFileDownload(
    JSON.stringify(exportPayload, null, 2),
    'RentFlow_Personal_Data_Export.json',
    'application/json;charset=utf-8'
  );
};

export const downloadHandbookGuideDoc = (guideTitle = '2026 Resident Maintenance Manual') => {
  const lines = [
    `RENTFLOW OFFICIAL RESIDENT TECHNICAL MANUAL`,
    `========================================================================`,
    `Document Subject: ${guideTitle}`,
    `Applicable Property: Victoria Island Towers, All Residential Suites`,
    `Published by: Adeleke & Co. Asset Management Division`,
    '',
    '### 1. EMERGENCY SAFETY & CRITICAL PROTOCOLS',
    'In the event of a severe plumbing burst, active electrical sparking, or fire hazards,',
    'residents must immediately follow standard safety containment procedures:',
    'A. Evacuate the immediate hazard area and alert household members.',
    'B. Call the 24/7 Rapid Response Concierge Hotline at +234 803 000 0198.',
    'C. If safe to do so, isolate the main utility breaker or water shut-off valve.',
    '',
    '### 2. ELECTRICAL DISTRIBUTION & CIRCUIT BREAKERS GUIDE',
    'The main electrical distribution panel for your suite is located inside the hallway',
    'utility pantry. Every breaker is clearly labeled for Lighting, HVAC, Kitchen, and Plugs.',
    'If an appliance overloads and trips a circuit breaker:',
    '- Unplug all heavy appliances connected to that specific circuit zone.',
    '- Open the pantry distribution panel and identify the tripped switch (in middle position).',
    '- Firmly switch the breaker completely to the OFF position, pause for 10 seconds,',
    '  and then push it firmly back to the ON position to restore power.',
    '- If the breaker trips repeatedly, leave it OFF and log an emergency ticket via portal.',
    '',
    '### 3. AIR CONDITIONING CARE & HYGIENE PROCEDURES',
    'Your residence is equipped with high-efficiency inverter split cooling units.',
    'To maintain optimal air quality, prevent water condensation leaks, and reduce power bills:',
    '- Open the front grille of each AC indoor unit once every 30 days.',
    '- Remove the mesh dust filters and rinse gently under lukewarm tap water.',
    '- Allow filters to air-dry completely before reinstalling into the unit slots.',
    '- Never operate cooling units with open balcony doors or windows.',
    '- Quarterly deep chemical servicing is scheduled automatically by facility management.',
    '',
    '### 4. PLUMBING ISOLATION & WATER SHUT-OFF VALVES',
    'To prevent water damage during minor fixture replacements or sudden pipe leaks:',
    '- Individual angle isolation valves are situated directly beneath sink vanities and toilets.',
    '- Turn the chrome valve handle clockwise (to the right) until tight to stop water flow.',
    '- The Master Suite water shut-off valve governing the entire apartment is located inside',
    '  the laundry room closet behind metal inspection hatch B.',
    '',
    '### 5. WASTE MANAGEMENT & RECYCLING GUIDELINES',
    'Central trash chutes are located on each floor corridor. Please bag and securely tie',
    'all domestic waste before disposal. Do not dispose of oversized cardboard boxes or glass',
    'down the chute; leave them in the service freight lobby for janitorial collection.'
  ];

  const cleanTitle = guideTitle.replace(/[^a-zA-Z0-9_-]/g, '_');
  const blob = buildPurePDFBlob(`${guideTitle} - RentFlow Guide`, lines);
  triggerFileDownload(blob, `RentFlow_Guide_${cleanTitle}.pdf`, 'application/pdf');
};
